version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: tsz30_db
      POSTGRES_USER: tsz30_user
      POSTGRES_PASSWORD: tsz30_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U tsz30_user -d tsz30_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build: .
    environment:
      - DATABASE_URL=postgresql://tsz30_user:tsz30_password@db:5432/tsz30_db
      - SECRET_KEY=your-secret-key-here
      - DEBUG=False
      - ALLOWED_HOSTS=toisozvezdoi.kz,www.toisozvezdoi.kz,localhost,127.0.0.1
      - CSRF_TRUSTED_ORIGINS=https://toisozvezdoi.kz,https://www.toisozvezdoi.kz
      - STATIC_URL=/static/
      - MEDIA_URL=/media/
      - SECURE_SSL_REDIRECT=True
      - SECURE_PROXY_SSL_HEADER=HTTP_X_FORWARDED_PROTO,https
      - SESSION_COOKIE_SECURE=True
      - CSRF_COOKIE_SECURE=True
      - SECURE_HSTS_SECONDS=31536000
      - SECURE_HSTS_INCLUDE_SUBDOMAINS=True
      - SECURE_HSTS_PRELOAD=True
    volumes:
      - media_files:/app/media
      - static_files:/app/staticfiles
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - static_files:/app/staticfiles:ro
      - media_files:/app/media:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - web
    restart: unless-stopped

volumes:
  postgres_data:
  static_files:
  media_files: 