# Generated by Django 5.1.6 on 2025-05-29 16:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='busydate',
            options={},
        ),
        migrations.RemoveField(
            model_name='busydate',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='busydate',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='BookingProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Ожидает ответа'), ('accepted', 'Принято'), ('rejected', 'Отклонено')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_proposals', to='main.order')),
                ('performer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_proposals', to=settings.AUTH_USER_MODEL)),
                ('tariff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.tariff')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('order', 'performer', 'date')},
            },
        ),
    ]
