# Generated by Django 3.2.25 on 2025-07-15 10:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_busydate_options_remove_busydate_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='performer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages_performer', to=settings.AUTH_USER_MODEL),
        ),
    ]
