# Generated by Django 3.2.25 on 2025-07-16 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_message_performer'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='selected_performers',
            field=models.JSONField(blank=True, default=dict, help_text='Выбранные исполнители по услугам'),
        ),
    ]
