# Generated by Django 3.2.25 on 2025-07-16 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_order_selected_performers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='selected_performers',
            field=models.JSONField(blank=True, default=dict, help_text='Выбранные исполнители по услугам: {service_type: performer_id}'),
        ),
    ]
