# Generated by Django 3.2.25 on 2025-07-31 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20250730_1453'),
        ('main', '0007_alter_order_description'),
    ]

    operations = [
    ]
