# Generated by Django 5.2.4 on 2025-08-07 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_order_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderresponse',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает'), ('accepted', 'Принят'), ('rejected', 'Отклонен'), ('cancelled', 'Отменен')], default='pending', max_length=20),
        ),
    ]
