# Generated by Django 5.2.4 on 2025-08-07 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_orderresponse_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='budget_max',
        ),
        migrations.RemoveField(
            model_name='order',
            name='budget_min',
        ),
        migrations.AddField(
            model_name='order',
            name='budget',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Бюджет'),
        ),
    ]
