# Generated by Django 5.2.4 on 2025-08-07 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_remove_order_budget_max_remove_order_budget_min_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='portfolio',
            options={'ordering': ['-created_at'], 'verbose_name': 'Портфолио', 'verbose_name_plural': 'Портфолио'},
        ),
        migrations.AddField(
            model_name='portfolio',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='duration',
            field=models.IntegerField(blank=True, help_text='Длительность видео в секундах', null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='file_size',
            field=models.BigIntegerField(blank=True, help_text='Размер файла в байтах', null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='media_type',
            field=models.CharField(choices=[('image', 'Фото'), ('video', 'Видео')], default='image', max_length=10),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='portfolio/thumbnails/'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='portfolio/videos/'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='portfolio/'),
        ),
    ]
