# Generated by Django 5.2.4 on 2025-08-07 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_portfolio_options_portfolio_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='experience_years',
            field=models.IntegerField(default=0, verbose_name='Опыт работы (лет)'),
        ),
    ]
