# Generated by Django 5.2.4 on 2025-08-08 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_user_experience_years'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='event_type',
            field=models.CharField(choices=[('wedding', 'Свадьба'), ('birthday', 'День рождения'), ('corporate', 'Корпоратив'), ('anniversary', 'Юбилей'), ('graduation', 'Выпускной'), ('other', 'Другое')], max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='services',
            field=models.JSONField(default=list),
        ),
    ]
